/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("advent.of.code.kotlin-application-conventions")
}

dependencies {
}

application {
    // Define the main class for the application.
    mainClass.set("advent.of.code.app.day10.AppKt")
}
